apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ShinobiSlayer/actions-deployment.git
    targetRevision: main
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
